//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.05 at 10:27:42 AM CEST 
//


package org.jbiowhcore.utility.fileformats.pride.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The GelFreeIdentification element (complex) is a concrete implementation of the abstract
 *                 IdentificationType element, used to hold details of identifications that have arisen from techniques
 *                 other than gel eletrophoresis, for example LC-MS/MS.
 *             
 * 
 * <p>Java class for GelFreeIdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GelFreeIdentificationType">
 *   &lt;complexContent>
 *     &lt;extension base="{}IdentificationType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GelFreeIdentificationType")
public class GelFreeIdentificationType
    extends IdentificationType
{


}
