//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.05 at 10:27:42 AM CEST 
//


package org.jbiowhcore.utility.fileformats.pride.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jbiowhcore.utility.fileformats.pride.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jbiowh.core.utility.fileformats.pride.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InstrumentDescriptionType }
     * 
     */
    public InstrumentDescriptionType createInstrumentDescriptionType() {
        return new InstrumentDescriptionType();
    }

    /**
     * Create an instance of {@link DataProcessingType }
     * 
     */
    public DataProcessingType createDataProcessingType() {
        return new DataProcessingType();
    }

    /**
     * Create an instance of {@link SpectrumDescType }
     * 
     */
    public SpectrumDescType createSpectrumDescType() {
        return new SpectrumDescType();
    }

    /**
     * Create an instance of {@link PeakListBinaryType }
     * 
     */
    public PeakListBinaryType createPeakListBinaryType() {
        return new PeakListBinaryType();
    }

    /**
     * Create an instance of {@link SpectrumSettingsType }
     * 
     */
    public SpectrumSettingsType createSpectrumSettingsType() {
        return new SpectrumSettingsType();
    }

    /**
     * Create an instance of {@link SpectrumSettingsType.AcqSpecification }
     * 
     */
    public SpectrumSettingsType.AcqSpecification createSpectrumSettingsTypeAcqSpecification() {
        return new SpectrumSettingsType.AcqSpecification();
    }

    /**
     * Create an instance of {@link ExperimentType }
     * 
     */
    public ExperimentType createExperimentType() {
        return new ExperimentType();
    }

    /**
     * Create an instance of {@link ExperimentType.MzData }
     * 
     */
    public ExperimentType.MzData createExperimentTypeMzData() {
        return new ExperimentType.MzData();
    }

    /**
     * Create an instance of {@link ExperimentType.MzData.SpectrumList }
     * 
     */
    public ExperimentType.MzData.SpectrumList createExperimentTypeMzDataSpectrumList() {
        return new ExperimentType.MzData.SpectrumList();
    }

    /**
     * Create an instance of {@link ExperimentType.Protocol }
     * 
     */
    public ExperimentType.Protocol createExperimentTypeProtocol() {
        return new ExperimentType.Protocol();
    }

    /**
     * Create an instance of {@link ExperimentCollection }
     * 
     */
    public ExperimentCollection createExperimentCollection() {
        return new ExperimentCollection();
    }

    /**
     * Create an instance of {@link ProjectList }
     * 
     */
    public ProjectList createProjectList() {
        return new ProjectList();
    }

    /**
     * Create an instance of {@link UserParamType }
     * 
     */
    public UserParamType createUserParamType() {
        return new UserParamType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link SoftwareType }
     * 
     */
    public SoftwareType createSoftwareType() {
        return new SoftwareType();
    }

    /**
     * Create an instance of {@link SimpleReference }
     * 
     */
    public SimpleReference createSimpleReference() {
        return new SimpleReference();
    }

    /**
     * Create an instance of {@link SupDataType }
     * 
     */
    public SupDataType createSupDataType() {
        return new SupDataType();
    }

    /**
     * Create an instance of {@link PrecursorType }
     * 
     */
    public PrecursorType createPrecursorType() {
        return new PrecursorType();
    }

    /**
     * Create an instance of {@link SupDataBinaryType }
     * 
     */
    public SupDataBinaryType createSupDataBinaryType() {
        return new SupDataBinaryType();
    }

    /**
     * Create an instance of {@link SupDescType }
     * 
     */
    public SupDescType createSupDescType() {
        return new SupDescType();
    }

    /**
     * Create an instance of {@link FragmentIonType }
     * 
     */
    public FragmentIonType createFragmentIonType() {
        return new FragmentIonType();
    }

    /**
     * Create an instance of {@link GelFreeIdentificationType }
     * 
     */
    public GelFreeIdentificationType createGelFreeIdentificationType() {
        return new GelFreeIdentificationType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link SourceFileType }
     * 
     */
    public SourceFileType createSourceFileType() {
        return new SourceFileType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link TwoDimensionalIdentificationType }
     * 
     */
    public TwoDimensionalIdentificationType createTwoDimensionalIdentificationType() {
        return new TwoDimensionalIdentificationType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link Modification }
     * 
     */
    public Modification createModification() {
        return new Modification();
    }

    /**
     * Create an instance of {@link Peptide }
     * 
     */
    public Peptide createPeptide() {
        return new Peptide();
    }

    /**
     * Create an instance of {@link SpectrumType }
     * 
     */
    public SpectrumType createSpectrumType() {
        return new SpectrumType();
    }

    /**
     * Create an instance of {@link AdminType }
     * 
     */
    public AdminType createAdminType() {
        return new AdminType();
    }

    /**
     * Create an instance of {@link SimpleGel }
     * 
     */
    public SimpleGel createSimpleGel() {
        return new SimpleGel();
    }

    /**
     * Create an instance of {@link CvParamType }
     * 
     */
    public CvParamType createCvParamType() {
        return new CvParamType();
    }

    /**
     * Create an instance of {@link CvLookupType }
     * 
     */
    public CvLookupType createCvLookupType() {
        return new CvLookupType();
    }

    /**
     * Create an instance of {@link InstrumentDescriptionType.AnalyzerList }
     * 
     */
    public InstrumentDescriptionType.AnalyzerList createInstrumentDescriptionTypeAnalyzerList() {
        return new InstrumentDescriptionType.AnalyzerList();
    }

    /**
     * Create an instance of {@link DataProcessingType.Software }
     * 
     */
    public DataProcessingType.Software createDataProcessingTypeSoftware() {
        return new DataProcessingType.Software();
    }

    /**
     * Create an instance of {@link SpectrumDescType.PrecursorList }
     * 
     */
    public SpectrumDescType.PrecursorList createSpectrumDescTypePrecursorList() {
        return new SpectrumDescType.PrecursorList();
    }

    /**
     * Create an instance of {@link PeakListBinaryType.Data }
     * 
     */
    public PeakListBinaryType.Data createPeakListBinaryTypeData() {
        return new PeakListBinaryType.Data();
    }

    /**
     * Create an instance of {@link SpectrumSettingsType.SpectrumInstrument }
     * 
     */
    public SpectrumSettingsType.SpectrumInstrument createSpectrumSettingsTypeSpectrumInstrument() {
        return new SpectrumSettingsType.SpectrumInstrument();
    }

    /**
     * Create an instance of {@link SpectrumSettingsType.AcqSpecification.Acquisition }
     * 
     */
    public SpectrumSettingsType.AcqSpecification.Acquisition createSpectrumSettingsTypeAcqSpecificationAcquisition() {
        return new SpectrumSettingsType.AcqSpecification.Acquisition();
    }

    /**
     * Create an instance of {@link ExperimentType.MzData.Description }
     * 
     */
    public ExperimentType.MzData.Description createExperimentTypeMzDataDescription() {
        return new ExperimentType.MzData.Description();
    }

    /**
     * Create an instance of {@link ExperimentType.MzData.SpectrumList.Spectrum }
     * 
     */
    public ExperimentType.MzData.SpectrumList.Spectrum createExperimentTypeMzDataSpectrumListSpectrum() {
        return new ExperimentType.MzData.SpectrumList.Spectrum();
    }

    /**
     * Create an instance of {@link ExperimentType.Protocol.ProtocolSteps }
     * 
     */
    public ExperimentType.Protocol.ProtocolSteps createExperimentTypeProtocolProtocolSteps() {
        return new ExperimentType.Protocol.ProtocolSteps();
    }

}
