//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.05 at 10:27:42 AM CEST 
//


package org.jbiowhcore.utility.fileformats.pride.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProjectList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProjectList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Experiment" type="{}ExperimentType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProjectList", propOrder = {
    "experiment"
})
@XmlSeeAlso({
    ExperimentCollection.class
})
public class ProjectList {

    @XmlElement(name = "Experiment", required = true)
    protected ExperimentType experiment;

    /**
     * Gets the value of the experiment property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentType }
     *     
     */
    public ExperimentType getExperiment() {
        return experiment;
    }

    /**
     * Sets the value of the experiment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentType }
     *     
     */
    public void setExperiment(ExperimentType value) {
        this.experiment = value;
    }

}
