//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.07 at 02:11:31 PM CET 
//
package org.jbiowhcore.utility.fileformats.orthoxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * A database element contains all genes from a single database/source.
 *
 *
 * <p>
 * Java class for database complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="database">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="genes" type="{http://orthoXML.org/2011/}genes"/>
 *       &lt;/sequence>
 *       &lt;attribute name="geneLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="protLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="transcriptLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "database", propOrder = {
    "genes"
})
public class Database {

    @XmlElement(required = true)
    protected Genes genes;
    @XmlAttribute(name = "geneLink")
    @XmlSchemaType(name = "anyURI")
    protected String geneLink;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "protLink")
    @XmlSchemaType(name = "anyURI")
    protected String protLink;
    @XmlAttribute(name = "transcriptLink")
    @XmlSchemaType(name = "anyURI")
    protected String transcriptLink;
    @XmlAttribute(name = "version", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String version;

    /**
     * Gets the value of the genes property.
     *
     * @return possible object is {@link Genes }
     *
     */
    public Genes getGenes() {
        return genes;
    }

    /**
     * Sets the value of the genes property.
     *
     * @param value allowed object is {@link Genes }
     *
     */
    public void setGenes(Genes value) {
        this.genes = value;
    }

    /**
     * Gets the value of the geneLink property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGeneLink() {
        return geneLink;
    }

    /**
     * Sets the value of the geneLink property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGeneLink(String value) {
        this.geneLink = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the protLink property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getProtLink() {
        return protLink;
    }

    /**
     * Sets the value of the protLink property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setProtLink(String value) {
        this.protLink = value;
    }

    /**
     * Gets the value of the transcriptLink property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTranscriptLink() {
        return transcriptLink;
    }

    /**
     * Sets the value of the transcriptLink property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTranscriptLink(String value) {
        this.transcriptLink = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }

    @Override
    public String toString() {
        return "Database{" + "geneLink=" + geneLink
                + ", name=" + name
                + ", protLink=" + protLink
                + ", transcriptLink=" + transcriptLink
                + ", version=" + version + "}\n"
                + genes;
    }
}
