//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.07 at 02:11:31 PM CET 
//
package org.jbiowhcore.utility.fileformats.orthoxml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="notes" type="{http://orthoXML.org/2011/}notes" minOccurs="0"/>
 *         &lt;element name="species" type="{http://orthoXML.org/2011/}species" maxOccurs="unbounded"/>
 *         &lt;element name="scores" type="{http://orthoXML.org/2011/}scores" minOccurs="0"/>
 *         &lt;element name="groups" type="{http://orthoXML.org/2011/}groups"/>
 *       &lt;/sequence>
 *       &lt;attribute name="origin" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="originVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "notes",
    "species",
    "scores",
    "groups"
})
@XmlRootElement(name = "orthoXML")
public class OrthoXML {

    protected Notes notes;
    @XmlElement(required = true)
    protected List<Species> species;
    protected Scores scores;
    @XmlElement(required = true)
    protected Groups groups;
    @XmlAttribute(name = "origin", required = true)
    protected String origin;
    @XmlAttribute(name = "version", required = true)
    protected BigDecimal version;
    @XmlAttribute(name = "originVersion", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String originVersion;

    /**
     * Gets the value of the notes property.
     *
     * @return possible object is {@link Notes }
     *
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     *
     * @param value allowed object is {@link Notes }
     *
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the species property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the species property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecies().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Species }
     *
     *
     */
    public List<Species> getSpecies() {
        if (species == null) {
            species = new ArrayList<Species>();
        }
        return this.species;
    }

    /**
     * Gets the value of the scores property.
     *
     * @return possible object is {@link Scores }
     *
     */
    public Scores getScores() {
        return scores;
    }

    /**
     * Sets the value of the scores property.
     *
     * @param value allowed object is {@link Scores }
     *
     */
    public void setScores(Scores value) {
        this.scores = value;
    }

    /**
     * Gets the value of the groups property.
     *
     * @return possible object is {@link Groups }
     *
     */
    public Groups getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     *
     * @param value allowed object is {@link Groups }
     *
     */
    public void setGroups(Groups value) {
        this.groups = value;
    }

    /**
     * Gets the value of the origin property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

    /**
     * Gets the value of the originVersion property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getOriginVersion() {
        return originVersion;
    }

    /**
     * Sets the value of the originVersion property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setOriginVersion(String value) {
        this.originVersion = value;
    }

    @Override
    public String toString() {
        StringBuilder b = new StringBuilder();
        
        if (species != null){
            for(Species d : species){
                b.append("\t").append(d).append("\n");
            }
        }
        return "OrthoXML{" + "origin=" + origin + ", version=" + version + ", originVersion=" + originVersion + '}';
    }

}
