//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.07 at 02:11:31 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://orthoXML.org/2011/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.jbiowhcore.utility.fileformats.orthoxml;
