//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.07 at 02:11:31 PM CET 
//
package org.jbiowhcore.utility.fileformats.orthoxml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * The gene element represents a single gene, protein or transcript. It is in
 * fact a set of identifiers: one internal identifier that is used to link from
 * geneRef elements in ortholog clusters and gene identifiers, transcript
 * identifiers and protein identifiers to identify the molecule. The proper term
 * for this element would therefore rather be molecule. However, as the general
 * purpose of orthoXML is to represent orthology data for genes the term gene is
 * used instead. Gene, protein and transcipt identifiers are optional but at
 * least one of the three should be given. The source database of the gene is
 * defined through the database element in which the gene element lies and the
 * identifiers should stem from this source.
 *
 *
 * <p>
 * Java class for gene complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="gene">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="geneId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="protId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="transcriptId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gene")
public class Gene {

    @XmlAttribute(name = "geneId")
    protected String geneId;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "protId")
    protected String protId;
    @XmlAttribute(name = "transcriptId")
    protected String transcriptId;

    /**
     * Gets the value of the geneId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGeneId() {
        return geneId;
    }

    /**
     * Sets the value of the geneId property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGeneId(String value) {
        this.geneId = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the protId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getProtId() {
        return protId;
    }

    /**
     * Sets the value of the protId property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setProtId(String value) {
        this.protId = value;
    }

    /**
     * Gets the value of the transcriptId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTranscriptId() {
        return transcriptId;
    }

    /**
     * Sets the value of the transcriptId property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTranscriptId(String value) {
        this.transcriptId = value;
    }

    @Override
    public String toString() {
        return "Gene{" + "geneId=" + geneId + ", id=" + id + ", protId=" + protId + ", transcriptId=" + transcriptId + '}';
    }
}
