//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.07 at 02:11:31 PM CET 
//
package org.jbiowhcore.utility.fileformats.orthoxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * A group of genes or nested groups. In case of a orothologGroup element, all
 * genes in the group or in the nested groups are orthologs to each other i.e.
 * stem from the same gene in the last common ancester of the species. In case
 * of a paralogGroup the genes are paralogs to each other. Subgroups within the
 * group allow the represention of phylogenetic trees. For more details and
 * examples see http://orthoxml.org/orthoxml_doc.html.
 *
 *
 * <p>
 * Java class for group complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="group">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="score" type="{http://orthoXML.org/2011/}score" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="property" type="{http://orthoXML.org/2011/}property" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="2">
 *           &lt;element name="geneRef" type="{http://orthoXML.org/2011/}geneRef"/>
 *           &lt;element name="paralogGroup" type="{http://orthoXML.org/2011/}group"/>
 *           &lt;element name="orthologGroup" type="{http://orthoXML.org/2011/}group"/>
 *         &lt;/choice>
 *         &lt;element name="notes" type="{http://orthoXML.org/2011/}notes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "group", propOrder = {
    "score",
    "property",
    "geneRefOrParalogGroupOrOrthologGroup",
    "notes"
})
public class Group {

    protected List<Score> score;
    protected List<Property> property;
    @XmlElementRefs({
        @XmlElementRef(name = "paralogGroup", namespace = "http://orthoXML.org/2011/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "geneRef", namespace = "http://orthoXML.org/2011/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "orthologGroup", namespace = "http://orthoXML.org/2011/", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> geneRefOrParalogGroupOrOrthologGroup;
    protected Notes notes;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the score property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the score property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScore().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Score }
     *
     *
     */
    public List<Score> getScore() {
        if (score == null) {
            score = new ArrayList<>();
        }
        return this.score;
    }

    /**
     * Gets the value of the property property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the property property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     *
     *
     */
    public List<Property> getProperty() {
        if (property == null) {
            property = new ArrayList<>();
        }
        return this.property;
    }

    /**
     * Gets the value of the geneRefOrParalogGroupOrOrthologGroup property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the geneRefOrParalogGroupOrOrthologGroup
     * property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeneRefOrParalogGroupOrOrthologGroup().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list      {@link JAXBElement }{@code <}{@link GeneRef }{@code >}
     * {@link JAXBElement }{@code <}{@link Group }{@code >}
     * {@link JAXBElement }{@code <}{@link Group }{@code >}
     *
     *
     */
    public List<JAXBElement<?>> getGeneRefOrParalogGroupOrOrthologGroup() {
        if (geneRefOrParalogGroupOrOrthologGroup == null) {
            geneRefOrParalogGroupOrOrthologGroup = new ArrayList<>();
        }
        return this.geneRefOrParalogGroupOrOrthologGroup;
    }

    /**
     * Gets the value of the notes property.
     *
     * @return possible object is {@link Notes }
     *
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     *
     * @param value allowed object is {@link Notes }
     *
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    @Override
    public String toString() {
        StringBuilder b = new StringBuilder();
        if (geneRefOrParalogGroupOrOrthologGroup != null){
            for(JAXBElement<?> d: geneRefOrParalogGroupOrOrthologGroup){
                b.append("\t\t").append(d.getValue()).append("\n");
            }
        }
        return "Group{" + "id=" + id + "}\n" + b.toString();
    }

}
