//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.07 at 02:11:31 PM CET 
//
package org.jbiowhcore.utility.fileformats.orthoxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * Represents the list of ortholog groups. Note that the purpose of OrthoXML is
 * to store orthology assignment hence on the top level only ortholog groups are
 * allowed.
 *
 *
 * <p>
 * Java class for groups complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="groups">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orthologGroup" type="{http://orthoXML.org/2011/}group" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "groups", propOrder = {
    "orthologGroup"
})
public class Groups {

    @XmlElement(required = true)
    protected List<Group> orthologGroup;

    /**
     * Gets the value of the orthologGroup property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the orthologGroup property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrthologGroup().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Group }
     *
     *
     */
    public List<Group> getOrthologGroup() {
        if (orthologGroup == null) {
            orthologGroup = new ArrayList<Group>();
        }
        return this.orthologGroup;
    }

    @Override
    public String toString() {        
        if (orthologGroup != null) {
            StringBuilder b = new StringBuilder();
            for(Group g : orthologGroup){
                b.append("\t").append(g).append("\n");
            }
            return b.toString();
        }

        return "";
    }

}
