//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.07 at 02:11:31 PM CET 
//


package org.jbiowhcore.utility.fileformats.orthoxml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jbiowhcore.utility.fileformats.orthoxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GroupOrthologGroup_QNAME = new QName("http://orthoXML.org/2011/", "orthologGroup");
    private final static QName _GroupParalogGroup_QNAME = new QName("http://orthoXML.org/2011/", "paralogGroup");
    private final static QName _GroupGeneRef_QNAME = new QName("http://orthoXML.org/2011/", "geneRef");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jbiowhcore.utility.fileformats.orthoxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrthoXML }
     * 
     */
    public OrthoXML createOrthoXML() {
        return new OrthoXML();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link Species }
     * 
     */
    public Species createSpecies() {
        return new Species();
    }

    /**
     * Create an instance of {@link Scores }
     * 
     */
    public Scores createScores() {
        return new Scores();
    }

    /**
     * Create an instance of {@link Groups }
     * 
     */
    public Groups createGroups() {
        return new Groups();
    }

    /**
     * Create an instance of {@link Gene }
     * 
     */
    public Gene createGene() {
        return new Gene();
    }

    /**
     * Create an instance of {@link Genes }
     * 
     */
    public Genes createGenes() {
        return new Genes();
    }

    /**
     * Create an instance of {@link Score }
     * 
     */
    public Score createScore() {
        return new Score();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link ScoreDef }
     * 
     */
    public ScoreDef createScoreDef() {
        return new ScoreDef();
    }

    /**
     * Create an instance of {@link GeneRef }
     * 
     */
    public GeneRef createGeneRef() {
        return new GeneRef();
    }

    /**
     * Create an instance of {@link Database }
     * 
     */
    public Database createDatabase() {
        return new Database();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Group }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orthoXML.org/2011/", name = "orthologGroup", scope = Group.class)
    public JAXBElement<Group> createGroupOrthologGroup(Group value) {
        return new JAXBElement<>(_GroupOrthologGroup_QNAME, Group.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Group }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orthoXML.org/2011/", name = "paralogGroup", scope = Group.class)
    public JAXBElement<Group> createGroupParalogGroup(Group value) {
        return new JAXBElement<>(_GroupParalogGroup_QNAME, Group.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeneRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orthoXML.org/2011/", name = "geneRef", scope = Group.class)
    public JAXBElement<GeneRef> createGroupGeneRef(GeneRef value) {
        return new JAXBElement<>(_GroupGeneRef_QNAME, GeneRef.class, Group.class, value);
    }

}
