//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.05 at 10:27:42 AM CEST 
//


package org.jbiowhcore.utility.fileformats.pride.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This is a concrete implementation of the abstract Identification element. This is used to
 *                 represent identifications based upon 2D Gel Electrophoresis. Details of the gel, location of the spot,
 *                 pI and molecular weight are included in this identification element.
 *             
 * 
 * <p>Java class for TwoDimensionalIdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TwoDimensionalIdentificationType">
 *   &lt;complexContent>
 *     &lt;extension base="{}IdentificationType">
 *       &lt;sequence>
 *         &lt;element name="Gel" type="{}SimpleGel" minOccurs="0"/>
 *         &lt;element name="GelLocation" type="{}Point" minOccurs="0"/>
 *         &lt;element name="MolecularWeight" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pI" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TwoDimensionalIdentificationType", propOrder = {
    "gel",
    "gelLocation",
    "molecularWeight",
    "pi"
})
public class TwoDimensionalIdentificationType
    extends IdentificationType
{

    @XmlElement(name = "Gel")
    protected SimpleGel gel;
    @XmlElement(name = "GelLocation")
    protected Point gelLocation;
    @XmlElement(name = "MolecularWeight")
    protected Double molecularWeight;
    @XmlElement(name = "pI")
    protected Double pi;

    /**
     * Gets the value of the gel property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleGel }
     *     
     */
    public SimpleGel getGel() {
        return gel;
    }

    /**
     * Sets the value of the gel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleGel }
     *     
     */
    public void setGel(SimpleGel value) {
        this.gel = value;
    }

    /**
     * Gets the value of the gelLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Point }
     *     
     */
    public Point getGelLocation() {
        return gelLocation;
    }

    /**
     * Sets the value of the gelLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Point }
     *     
     */
    public void setGelLocation(Point value) {
        this.gelLocation = value;
    }

    /**
     * Gets the value of the molecularWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMolecularWeight() {
        return molecularWeight;
    }

    /**
     * Sets the value of the molecularWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMolecularWeight(Double value) {
        this.molecularWeight = value;
    }

    /**
     * Gets the value of the pi property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPI() {
        return pi;
    }

    /**
     * Sets the value of the pi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPI(Double value) {
        this.pi = value;
    }

}
