//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.04 at 12:26:35 PM CEST 
//
package org.jbiowhcore.utility.fileformats.bioml.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * The Group XML class
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "protein",
    "group",
    "note"
})
@XmlRootElement(name = "group")
public class Group {

    @XmlAttribute(name = "state")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String state;
    @XmlAttribute(name = "label")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String label;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "mh")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String mh;
    @XmlAttribute(name = "z")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String z;
    @XmlAttribute(name = "rt")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rt;
    @XmlAttribute(name = "expect")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String expect;
    @XmlAttribute(name = "type")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "sumI")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sumI;
    @XmlAttribute(name = "maxI")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String maxI;
    @XmlAttribute(name = "fI")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fI;
    @XmlAttribute(name = "act")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String act;
    protected List<Protein> protein;
    protected List<Group> group;
    protected List<Note> note;

    /**
     * Gets the value of the state property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    public String getMh() {
        return mh;
    }

    public void setMh(String mh) {
        this.mh = mh;
    }

    public String getZ() {
        return z;
    }

    public void setZ(String z) {
        this.z = z;
    }

    public String getRt() {
        return rt;
    }

    public void setRt(String rt) {
        this.rt = rt;
    }

    public String getExpect() {
        return expect;
    }

    public void setExpect(String expect) {
        this.expect = expect;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSumI() {
        return sumI;
    }

    public void setSumI(String sumI) {
        this.sumI = sumI;
    }

    public String getMaxI() {
        return maxI;
    }

    public void setMaxI(String maxI) {
        this.maxI = maxI;
    }

    public String getfI() {
        return fI;
    }

    public void setfI(String fI) {
        this.fI = fI;
    }

    public String getAct() {
        return act;
    }

    public void setAct(String act) {
        this.act = act;
    }

    public List<Protein> getProtein() {
        if (protein == null) {
            protein = new ArrayList();
        }
        return protein;
    }

    public List<Group> getGroup() {
        if (group == null) {
            group = new ArrayList();
        }
        return group;
    }

    public List<Note> getNote() {
        if (note == null) {
            note = new ArrayList();
        }
        return note;
    }

    public void setGroup(List<Group> group) {
        this.group = group;
    }

    public void setNote(List<Note> note) {
        this.note = note;
    }

    public void setProtein(List<Protein> protein) {
        this.protein = protein;
    }

    @Override
    public String toString() {
        StringBuilder b = new StringBuilder();
        for (Protein p : getProtein()) {
            b.append("\t\t").append(p).append("\n");
        }
        for (Group g : getGroup()) {
            b.append("\t\t").append(g).append("\n");
        }
        for (Note n : getNote()) {
            b.append("\t\t").append(n).append("\n");
        }
        return "Group{"
                + "state=" + state
                + ", label=" + label
                + ", id=" + id
                + ", mh=" + mh
                + ", z=" + z
                + ", rt=" + rt
                + ", expect=" + expect
                + ", type=" + type
                + ", sumI=" + sumI
                + ", maxI=" + maxI
                + ", fI=" + fI
                + ", act=" + act + "}\n"
                + b.toString();
    }
}
