//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.04 at 12:26:35 PM CEST 
//
package org.jbiowhcore.utility.fileformats.bioml.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * This is the Protein XML parser class
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "note",
    "peptide"
})
@XmlRootElement(name = "protein")
public class Protein {

    @XmlAttribute(name = "state")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String state;
    @XmlAttribute(name = "label")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String label;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "uid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String uid;
    @XmlAttribute(name = "comp")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String comp;
    @XmlAttribute(name = "expect")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String expect;
    @XmlAttribute(name = "sumI")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sumI;
    protected List<Note> note;
    protected List<Peptide> peptide;

    /**
     * Gets the value of the state property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the comp property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getComp() {
        return comp;
    }

    /**
     * Sets the value of the comp property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setComp(String value) {
        this.comp = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getExpect() {
        return expect;
    }

    public void setExpect(String expect) {
        this.expect = expect;
    }

    public String getSumI() {
        return sumI;
    }

    public void setSumI(String sumI) {
        this.sumI = sumI;
    }

    public List<Note> getNote() {
        if (note == null) {
            note = new ArrayList();
        }
        return note;
    }

    public void setNote(List<Note> note) {
        this.note = note;
    }

    public List<Peptide> getPeptide() {
        if (peptide == null) {
            peptide = new ArrayList();
        }
        return peptide;
    }

    public void setPeptide(List<Peptide> peptide) {
        this.peptide = peptide;
    }

    @Override
    public String toString() {
        StringBuilder b = new StringBuilder();
        for (Note n : getNote()) {
            b.append("\t\t\t").append(n).append("\n");
        }
        for (Peptide p : getPeptide()) {
            b.append("\t\t\t").append(p).append("\n");
        }
        return "Protein{" + "state=" + state
                + ", label=" + label
                + ", id=" + id
                + ", uid=" + uid
                + ", comp=" + comp
                + ", expect=" + expect
                + ", sumI=" + sumI + "}\n"
                + b.toString();
    }
}
